services:
  frontend-endpoint:
    build: nginx-load-balancers
    restart: always
    volumes:
      - ./nginx-load-balancers/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend

  frontend:
    build: bastionbook-frontend
    restart: always
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:5000 wsgi:app
    deploy:
      mode: replicated
      replicas: 2
  
  backend-endpoint:
    build: nginx-load-balancers
    restart: always
    volumes:
      - ./nginx-load-balancers/backend-default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    build: bastionbook-backend
    deploy:
      mode: replicated
      replicas: 2
    platform: linux/x86_64
    restart: always
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:5000 wsgi:app 
    volumes:
      - ./bastionbook-backend/.aws:/home/bas10book/.aws
  
  
    